package cat.israel.spring.repo;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import cat.israel.spring.model.CriticosCotiz;

@Repository
@Transactional
public interface ICriticosCotizRepo extends JpaRepository<CriticosCotiz, Integer>{

	@Query(nativeQuery = true, value = "SELECT CDDESCRIPTOR, FECHA, PAIS, ORIGEN, 'D - 1' DIA, 'LABORABLES' CARGA_DEL_DESCRIPTOR "
			+ "FROM(SELECT COT.CDDESCRIPTOR, MAX(COT.FECHA) AS FECHA, DES.CDPAIS AS PAIS, DES.CDORIGEN AS ORIGEN "
			+ "     FROM COTIZ COT, DESCRIPTOR DES "
			+ "     WHERE COT.CDDESCRIPTOR IN ?1 "
			+ "     AND COT.CDDESCRIPTOR = DES.CDDESCRIPTOR GROUP BY COT.CDDESCRIPTOR, DES.CDPAIS, DES.CDORIGEN) "
			+ "WHERE FECHA < (CASE "
			+ "                        WHEN TO_CHAR(to_date(TRUNC(SYSDATE)),'D') in ('1') THEN TRUNC(SYSDATE -3) "
			+ "                        ELSE TRUNC(SYSDATE-1) END) "
			+ "UNION ALL "
			+ "SELECT CDDESCRIPTOR, FECHA, PAIS, ORIGEN, 'D - 1' DIA, 'DIARIO' FINDE_INCLUIDO "
			+ "FROM(SELECT COT.CDDESCRIPTOR, MAX(COT.FECHA) AS FECHA, DES.CDPAIS AS PAIS, DES.CDORIGEN AS ORIGEN "
			+ "     FROM COTIZ COT, DESCRIPTOR DES "
			+ "     WHERE COT.CDDESCRIPTOR IN ?2 "
			+ "     AND COT.CDDESCRIPTOR = DES.CDDESCRIPTOR GROUP BY COT.CDDESCRIPTOR, DES.CDPAIS, DES.CDORIGEN) "
			+ "WHERE FECHA < TRUNC(SYSDATE-1) "
			+ "UNION ALL "
			+ "SELECT CDDESCRIPTOR, FECHA, PAIS, ORIGEN, 'D' DIA, 'DIARIO' CARGA_DEL_DESCRIPTOR "
			+ "FROM(SELECT COT.CDDESCRIPTOR, MAX(COT.FECHA) AS FECHA, DES.CDPAIS AS PAIS, DES.CDORIGEN AS ORIGEN "
			+ "     FROM COTIZ COT, DESCRIPTOR DES "
			+ "     WHERE COT.CDDESCRIPTOR IN ?3 "
			+ "     AND COT.CDDESCRIPTOR = DES.CDDESCRIPTOR GROUP BY COT.CDDESCRIPTOR, DES.CDPAIS, DES.CDORIGEN) "
			+ "WHERE FECHA < TRUNC(SYSDATE) "
			+ "UNION ALL "
			+ "SELECT CDDESCRIPTOR, FECHA, PAIS, ORIGEN, 'D - 2' DIA, 'DIARIO' CARGA_DEL_DESCRIPTOR "
			+ "FROM(SELECT COT.CDDESCRIPTOR, MAX(COT.FECHA) AS FECHA, DES.CDPAIS AS PAIS, DES.CDORIGEN AS ORIGEN "
			+ "     FROM COTIZ COT, DESCRIPTOR DES "
			+ "     WHERE COT.CDDESCRIPTOR IN ?4 "
			+ "     AND COT.CDDESCRIPTOR = DES.CDDESCRIPTOR GROUP BY COT.CDDESCRIPTOR, DES.CDPAIS, DES.CDORIGEN) "
			+ "WHERE FECHA < TRUNC(SYSDATE-2) "
			+ "UNION ALL "
			+ "SELECT CDDESCRIPTOR, FECHA, PAIS, ORIGEN, 'MENSUAL' DIA, 'MENSUAL' CARGA_DEL_DESCRIPTOR "
			+ "FROM(SELECT COT.CDDESCRIPTOR, MAX(COT.FECHA) AS FECHA, DES.CDPAIS AS PAIS, DES.CDORIGEN AS ORIGEN "
			+ "     FROM COTIZ COT, DESCRIPTOR DES "
			+ "     WHERE COT.CDDESCRIPTOR IN ?5 "
			+ "     AND COT.CDDESCRIPTOR = DES.CDDESCRIPTOR GROUP BY COT.CDDESCRIPTOR, DES.CDPAIS, DES.CDORIGEN) "
			+ "WHERE SUBSTR(TO_CHAR(FECHA),4) <> SUBSTR(ADD_MONTHS(TRUNC(SYSDATE), -2), 4) "
			+ "AND SUBSTR(TO_CHAR(TRUNC(SYSDATE)),1,2) > '15' "
			+ "ORDER BY CDDESCRIPTOR ASC ")
	List<CriticosCotiz> findByCountCotiz(List<Integer> cotiz_Dmenos1Lab, List<Integer> cotiz_Dmenos1Dia, 
										 List<Integer> cotiz_DDia, List<Integer> coti_Dmenos2Dia, 
										 List<Integer> cotiz_mensual);
}
